const CANVAS_SIZE = {
    WIDTH: 500,
    HEIGHT: 500
}
const CELL_SIDE_LENGTH =  50
const BOARD_ROW_COLUMN_COUNT = 8
const PIECE_RADIUS = 24

const CANVAS_COLOR = 'olive'
const LINE_COLOR = 'black'
const PIECE_COLOR_WHITE = 'white'
const PIECE_COLOR_BLACK = 'black'

export default {
    CANVAS_SIZE: CANVAS_SIZE,

    CELL_SIDE_LENGTH: CELL_SIDE_LENGTH,
    BOARD_ROW_COLUMN_COUNT: BOARD_ROW_COLUMN_COUNT,
    PIECE_RADIUS: PIECE_RADIUS,

    CANVAS_COLOR: CANVAS_COLOR,
    LINE_COLOR: LINE_COLOR,
    PIECE_COLOR_WHITE: PIECE_COLOR_WHITE,
    PIECE_COLOR_BLACK: PIECE_COLOR_BLACK
}