const BOARD_ROW_COLUMN_COUNT = 12
const CELL_SIDE_LENGTH =  30

const CANVAS_SIZE = {
    WIDTH: CELL_SIDE_LENGTH * (BOARD_ROW_COLUMN_COUNT + 2),
    HEIGHT: CELL_SIDE_LENGTH * (BOARD_ROW_COLUMN_COUNT + 2)
}

const PIECE_RADIUS = CELL_SIDE_LENGTH * 0.5 * 0.8

const TRACK_DISTANCE = 4

const CANVAS_COLOR = 'olive'
const LINE_COLOR = 'black'
const PIECE_COLOR_WHITE = 'white'
const PIECE_COLOR_BLACK = 'black'

const BORDER_WIDTH = 2

export default {
    CANVAS_SIZE: CANVAS_SIZE,

    CELL_SIDE_LENGTH: CELL_SIDE_LENGTH,
    BOARD_ROW_COLUMN_COUNT: BOARD_ROW_COLUMN_COUNT,
    PIECE_RADIUS: PIECE_RADIUS,
    TRACK_DISTANCE: TRACK_DISTANCE,

    CANVAS_COLOR: CANVAS_COLOR,
    LINE_COLOR: LINE_COLOR,
    PIECE_COLOR_WHITE: PIECE_COLOR_WHITE,
    PIECE_COLOR_BLACK: PIECE_COLOR_BLACK,

    BORDER_WIDTH: BORDER_WIDTH
}